PB-511: Django request context in logs - #minor
geoadmin/lib-py-logging-utilities pull request #61
Opened 2024-08-26 15:10 UTC by benschs

Add django request context to logs by filter configuration and middleware. Middleware adds the filter with the current request to the log handlers. Any logs will have the request information also added to the log record.

2024-08-27 12:49 UTC, ltshb commented on logging_utilities/request_middleware.py
> +        self.get_response = get_response
Might be a good idea to call `root` `rootLogger` to make the code easier to read/understand

2024-08-27 12:49 UTC, ltshb commented on logging_utilities/request_middleware.py
> +        for logger in self._find_handlers():
Here should it not be `handler` instead of `logger`?

2024-08-27 12:49 UTC, ltshb commented on tests/test_request_middleware.py
> +import json
Maybe rename  to `test_django_request_middleware.py`

2024-08-27 13:57 UTC, benschs commented on README.md
> +| `attributes` | list | None    | All request attributes that match any of the dotted keys of the list will be added to the jsonifiable object. When `None` then no attributes are added (default behav
I change between `request_attributes` and `attributes` during development. It should now be `attributes` consistently.

2024-08-27 14:01 UTC, benschs commented on logging_utilities/filters/django_append_request.py
> +                setattr(record, "request." + attr, val)
If there is no request, we only add the value "-" if `always_add` is explicitly set, so this is fine for me as it is.
I added a test case that explicitly sets `None` as request to demonstrate the behavior.

2024-08-27 21:53 UTC, boecklic approved these changes
Nice! Do you have an idea about possible performance impact of this solution? Since it's doing the processing for every request.

2024-08-27 21:53 UTC, boecklic commented on logging_utilities/filters/django_append_request.py
> +        request = self.request
in `__init__` the WSGIRequest is marked as optional and can be `None` if I understand correctly, so wouln't you need to check for `None` here and only continue if not None?

2024-08-27 21:53 UTC, boecklic commented on README.md
> +To add context information from the current request to each log record. For this the filter `DjangoAppendRequestFilter` must be added as well as the middleware `AddRequestToLogMiddleware`.
maybe you could be a little more verbose about the basic idea behind your solution with middleware and filter. With some not very deep understanding of how logging filters work this is not immediately obvious.

2024-08-27 21:53 UTC, boecklic commented on logging_utilities/django_middlewares/request_middleware.py
> +            response = self.get_response(w_request)
I'm not sure I understand this part: the `process_request` method already does a `return self.get_response(request)`, so if that `return` doesn't evaluate to sth `true`, why should calling it again result in a different outcome?

2024-08-27 21:53 UTC, boecklic commented on logging_utilities/django_middlewares/request_middleware.py
> +        """Return loggers part of root.
a little more information about what you do here, i.e. what `root_logger` is about would be helpful. This is not directly obvious also from django middleware doc I think

2024-08-28 09:57 UTC, ltshb requested changes
Could you verify if the filter approach is working in a multithread environment ? As discussed yesterday the logging loggers instance and filters are globals and it might be an issue with mutlithread environement.

2024-08-28 14:26 UTC, benschs commented
> Could you verify if the filter approach is working in a multithread environment ? As discussed yesterday the logging loggers instance and filters are globals and it might be an issue with mutlithread environement.

I could verify that this approach does not work in a multithreaded environment.
I will close this PR and open a new one with another approach of using thread variables.

2024-08-28 14:26 UTC, closed without merging